[package]
name = "rest_api"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.2"
reqwest = { version = "0.12", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "4.5"
ratatui = "0.29.0"

